# Generated by Django 5.2.4 on 2025-07-21 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_tutor'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Student',
        ),
    ]
