# Generated by Django 5.2.4 on 2025-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
