# Generated by Django 5.2.4 on 2025-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkclassroomassign',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
