# Generated by Django 5.2.4 on 2025-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_alter_homeworkclassroomassign_due_date'),
        ('students', '0002_rename_studentprofile_student'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('student', 'homework'), name='unique_student_homework'),
        ),
    ]
