# Generated by Django 5.2.4 on 2025-07-20 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('OTHER', 'Other')], default='OTHER')),
                ('classroom_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')])),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='classrooms', to='students.studentprofile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
