# Generated by Django 5.2.4 on 2025-07-24 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AddField(
            model_name='tutor',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter your telegram username', regex='^@[a-zA-Z][a-zA-Z0-9_]{4,31}$')]),
        ),
    ]
